apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiomuse
  labels:
    app: audiomuse
    component: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiomuse
      component: flask
  template:
    metadata:
      name: audiomuse
      labels:
        app: audiomuse
        component: flask
    spec:
      containers:
        - name: audiomuse
          image: ghcr.io/neptunehub/audiomuse-ai:0.7.12-beta@sha256:a0ed658b75d66044e3884cbf94acf5e016d4898bac4d5f0f25929b066c3e5f9c
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          envFrom:
            - secretRef:
                name: navidrome-credentials
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: mistral-api-credentials
            - secretRef:
                name: openai-api-credentials
            - configMapRef:
                name: audiomuse-ai-config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /app/temp_audio
              name: app-temp-audio
      restartPolicy: Always
      volumes:
        - name: app-temp-audio
          emptyDir: {}
