apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiomuse
  labels:
    app: audiomuse
    component: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiomuse
      component: flask
  template:
    metadata:
      name: audiomuse
      labels:
        app: audiomuse
        component: flask
    spec:
      containers:
        - name: audiomuse
          image: ghcr.io/neptunehub/audiomuse-ai:0.8.8@sha256:d3a01c5429225f9da4f1fee4b789cfec9c49f50e0829b528d0932c2b2509c99f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          envFrom:
            - secretRef:
                name: navidrome-credentials
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: mistral-api-credentials
            - secretRef:
                name: openai-api-credentials
            - secretRef:
                name: gemini-api-credentials
            - configMapRef:
                name: audiomuse-ai-config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /app/temp_audio
              name: app-temp-audio
      restartPolicy: Always
      volumes:
        - name: app-temp-audio
          emptyDir: {}
