apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiomuse
  labels:
    app: audiomuse
    component: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiomuse
      component: flask
  template:
    metadata:
      name: audiomuse
      labels:
        app: audiomuse
        component: flask
    spec:
      containers:
        - name: audiomuse
          image: ghcr.io/neptunehub/audiomuse-ai:0.8.12@sha256:3e90dd5d6e70690ee3fd65ecdc0a15ce65a2bf3f8e22732ad8036e2edaa1cb8b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          envFrom:
            - secretRef:
                name: navidrome-credentials
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: mistral-api-credentials
            - secretRef:
                name: openai-api-credentials
            - secretRef:
                name: gemini-api-credentials
            - configMapRef:
                name: audiomuse-ai-config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /app/temp_audio
              name: app-temp-audio
      restartPolicy: Always
      volumes:
        - name: app-temp-audio
          emptyDir: {}
