apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: audiomuse
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`audiomuse.internal`)
      middlewares:
        - name: security-headers
          namespace: kube-system
      services:
        - name: audiomuse
          port: 80
  tls:
    secretName: audiomuse-cert-tls
    domains:
      - main: audiomuse.internal
