apiVersion: v1
kind: Service
metadata:
  name: audiomuse
  labels:
    app: audiomuse
    component: flask
spec:
  selector:
    app: audiomuse
    component: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
