apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter-config
data:
  QBITTORRENT_BASE_URL: "http://qbittorrent"
  ENABLE_TRACKER: "true"
  ENABLE_HIGH_CARDINALITY: "true"
  ENABLE_LABEL_WITH_TRACKER: "true"
  ENABLE_LABEL_WITH_TAG: "true"
  ENABLE_INCREASED_CARDINALITY: "true"
