apiVersion: apps/v1
kind: Deployment
metadata:
  name: patchmon-frontend
  labels:
    app: patchmon-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patchmon-frontend
  template:
    metadata:
      name: patchmon-frontend
      labels:
        app: patchmon-frontend
    spec:
      containers:
        - name: patchmon-frontend
          image: ghcr.io/patchmon/patchmon-frontend:1.3.7@sha256:c81fe302f1a039a7f3b887b54e4d165b3c7b9ed9f1e60e8f99a982607ef2f6b8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
              name: http
          env:
            - name: BACKEND_HOST
              value: "patchmon-backend"
            - name: BACKEND_PORT
              value: "80"
      restartPolicy: Always
