apiVersion: apps/v1
kind: Deployment
metadata:
  name: patchmon-frontend
  labels:
    app: patchmon-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patchmon-frontend
  template:
    metadata:
      name: patchmon-frontend
      labels:
        app: patchmon-frontend
    spec:
      containers:
        - name: patchmon-frontend
          image: ghcr.io/patchmon/patchmon-frontend:1.4.2@sha256:002c9c9c1fe36961b0cf45a4b6723a6dafe97fa24ea4e39bd2fcc6b9ab73b71d
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
              name: http
          env:
            - name: BACKEND_HOST
              value: "patchmon-backend"
            - name: BACKEND_PORT
              value: "80"
      restartPolicy: Always
