apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: patchmon-public-cert
spec:
  secretName: patchmon-public-cert-tls
  commonName: patchmon.anshulg.direct
  dnsNames:
    - patchmon.anshulg.direct
  duration: 2160h0m0s
  renewBefore: 720h0m0s
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  subject:
    organizations:
      - Anshul Gupta
    organizationalUnits:
      - rpi5
    provinces:
      - California
    countries:
      - US
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: patchmon-public
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`patchmon.anshulg.direct`)
      services:
        - name: patchmon-frontend
          port: 80
  tls:
    secretName: patchmon-public-cert-tls
    domains:
      - main: patchmon.anshulg.direct
