services:
  home:
    image: ghcr.io/ansg191/anshulg-com:0.4.1@sha256:f8eeaee1f0e9336c34f5d4feba4dea7eba53a99dd90ba16bdf61070dd3d95dd5

    ports:
      - "127.0.0.1:4321:4321"

    restart: always
    user: "${COMPOSE_UID}:${COMPOSE_GID}"
    cap_drop:
      - ALL
    read_only: true

    env_file:
      - "/srv/home/home.env"

    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: 64M
        limits:
          cpus: "0.5"
          memory: 128M
