services:
  home:
    image: ghcr.io/ansg191/anshulg-com:0.3.5@sha256:424fc15c53d113ca7e627593b2d7d5abdb453a3b5cd39f0d18160f1caf48f079

    ports:
      - "127.0.0.1:4321:4321"

    restart: always
    user: "${COMPOSE_UID}:${COMPOSE_GID}"
    cap_drop:
      - ALL
    read_only: true

    env_file:
      - "/srv/home/home.env"

    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: 64M
        limits:
          cpus: "0.5"
          memory: 128M
