apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/security-context

namePrefix: autobrr-
labels:
  - pairs:
      app.kubernetes.io/name: autobrr
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/autobrr/autobrr
    newTag: v1.70.0@sha256:c691d8ddd5184c155d1732244519f0c09dc44559a7a0da14c6d0dc3edf7fcfb3

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=autobrr.internal
  - name: env-config
    literals:
      - TZ=America/Los_Angeles
  - name: scripts
    files:
      - freespace.sh=scripts/freespace.sh

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
