apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/security-context

namePrefix: autobrr-
labels:
  - pairs:
      app.kubernetes.io/name: autobrr
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/autobrr/autobrr
    newTag: v1.69.0@sha256:b14f129e3c6293a595e7a03e025e5c7dd4095bd96100f2889a226816ae39ee0a

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=autobrr.internal
  - name: env-config
    literals:
      - TZ=America/Los_Angeles
  - name: scripts
    files:
      - freespace.sh=scripts/freespace.sh

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
