apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/security-context

namePrefix: autobrr-
labels:
  - pairs:
      app.kubernetes.io/name: autobrr
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/autobrr/autobrr
    newTag: v1.73.0@sha256:6b0e57048087e5b7b626b0f02d39e91c8287d32691c26c709b3957227df12f7c

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=autobrr.internal
  - name: env-config
    literals:
      - TZ=America/Los_Angeles
  - name: scripts
    files:
      - freespace.sh=scripts/freespace.sh

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
