apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/tailscale

namePrefix: fasten-
labels:
  - pairs:
      app.kubernetes.io/name: fasten
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/fastenhealth/fasten-onprem
    newTag: main-v1.1.3@sha256:807c8cd60ec07afcf48d80ed492c02418cba2277508a7f50a2ec1c688286e90b

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=fasten.internal
      - TS_HOST=fasten
  - name: env-config
    literals:
      - HOST_PORT=8080

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
