apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/deployment

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: immich-
labels:
  - pairs:
      app.kubernetes.io/name: immich
    includeSelectors: true

images:
  - name: busybox
    newName: nginxinc/nginx-unprivileged
    newTag: 1.29.2@sha256:cb8d87bd242fcbd012f95169ac1dd60fc34db2341e616d4d71a279fa1a5e65f3

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=immich.internal
      - DIRECT_DOMAIN=immich.anshulg.direct
      - TS_HOST=immich
  - name: nginx-proxy-template
    files:
      - default.conf.template=default.conf.template
  - name: nginx-env
    literals:
      - UPSTREAM_HOST=192.168.1.10:30041

patches:
  - target:
      kind: Deployment
    path: patch-deployment.yaml
  - target:
      kind: Deployment
    path: patch-deployment2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
