apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/deployment

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: immich-
labels:
  - pairs:
      app.kubernetes.io/name: immich
    includeSelectors: true

images:
  - name: busybox
    newName: nginxinc/nginx-unprivileged
    newTag: 1.29.3@sha256:5366aa1ef633415d3fb30f8b5b2d824c4ae1c231a0f63358e7f39734fa5894c0

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=immich.internal
      - DIRECT_DOMAIN=immich.anshulg.direct
      - TS_HOST=immich
  - name: nginx-proxy-template
    files:
      - default.conf.template=default.conf.template
  - name: nginx-env
    literals:
      - UPSTREAM_HOST=192.168.1.10:30041

patches:
  - target:
      kind: Deployment
    path: patch-deployment.yaml
  - target:
      kind: Deployment
    path: patch-deployment2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
