apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/deployment
  - secrets.yaml

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: jellystat-
labels:
  - pairs:
      app.kubernetes.io/name: jellystat
    includeSelectors: true

images:
  - name: busybox
    newName: cyfershepard/jellystat
    newTag: 1.1.7@sha256:e182aedd122e13be511c59f0462e0d9e48a67c7341a5f3c1f11b7aa6ab6d2291

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=jellystat.internal
      - TS_HOST=jellystat
  - name: jellystat-config
    literals:
      - POSTGRES_IP=192.168.1.9
      - POSTGRES_PORT=5432
      - POSTGRES_USER=jellystat
      - POSTGRES_DB=jfstat
      - TZ=America/Los_Angeles

patches:
  - target:
      kind: Deployment
    path: patch-deployment.yaml
  - target:
      kind: Service
    path: patch-service.yaml
