apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: navidrome
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`navidrome.internal`)
      middlewares:
        - name: security-headers
          namespace: kube-system
      services:
        - name: navidrome
          port: 80
  tls:
    secretName: navidrome-cert-tls
    domains:
      - main: navidrome.internal
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: navidrome
      port:
        number: 80
  tls:
    - hosts:
        - navidrome
