apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: navidrome-public-cert
spec:
  secretName: navidrome-public-cert-tls
  commonName: navidrome.anshulg.direct
  dnsNames:
    - navidrome.anshulg.direct
  duration: 2160h0m0s
  renewBefore: 720h0m0s
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  subject:
    organizations:
      - Anshul Gupta
    organizationalUnits:
      - rpi5
    provinces:
      - California
    countries:
      - US
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: navidrome-public
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`navidrome.anshulg.direct`)
      services:
        - name: navidrome
          port: 80
  tls:
    secretName: navidrome-public-cert-tls
    domains:
      - main: navidrome.anshulg.direct
