apiVersion: apps/v1
kind: Deployment
metadata:
  name: import-watch
  labels:
    app: import-watch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: import-watch
  template:
    metadata:
      name: import-watch
      labels:
        app: import-watch
    spec:
      containers:
        - name: import-watch
          image: debian:13.2-slim@sha256:4bcb9db66237237d03b55b969271728dd3d955eaaa254b9db8a3db94550b1885
          imagePullPolicy: IfNotPresent
          command:
            - "/entrypoint.sh"
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: "/entrypoint.sh"
              name: script
              subPath: entrypoint.sh
            - mountPath: "/import"
              name: import
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: odroid-h4
      volumes:
        - name: script
          configMap:
            name: script
            defaultMode: 0755
        - name: import
          hostPath:
            path: "/data/BookImport"
