apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: ollama-
labels:
  - pairs:
      app.kubernetes.io/name: ollama
    includeSelectors: true

images:
  - name: busybox
    newName: ollama/ollama
    newTag: 0.15.2@sha256:76d0c003b27db65170e88ab319ff19c9bcee41ecb8177c52ab06921dfa13abdf

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=ollama.internal
      - DIRECT_DOMAIN=ollama.anshulg.direct
      - TS_HOST=ollama

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: Service
    path: patch-service.yaml
