apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: ollama-
labels:
  - pairs:
      app.kubernetes.io/name: ollama
    includeSelectors: true

images:
  - name: busybox
    newName: ollama/ollama
    newTag: 0.15.3@sha256:3970c9b21fc1286d2958dd33f9a4774d70a9b63d596c61ad0ed5b5dd28291dbe

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=ollama.internal
      - DIRECT_DOMAIN=ollama.anshulg.direct
      - TS_HOST=ollama

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: Service
    path: patch-service.yaml
