apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: ollama-
labels:
  - pairs:
      app.kubernetes.io/name: ollama
    includeSelectors: true

images:
  - name: busybox
    newName: ollama/ollama
    newTag: 0.12.9@sha256:889ae74bdb4aa541044574d3e5e5dedde3c682c8b7918b6792aa031e7dfc8f06

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=ollama.internal
      - DIRECT_DOMAIN=ollama.anshulg.direct
      - TS_HOST=ollama

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: Service
    path: patch-service.yaml
