apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-proxy
  labels:
    app: tracker-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker-proxy
  template:
    metadata:
      name: tracker-proxy
      labels:
        app: tracker-proxy
    spec:
      containers:
        - name: tracker-proxy
          image: caddy:2.10.2-alpine@sha256:953131cfea8e12bfe1c631a36308e9660e4389f0c3dfb3be957044d3ac92d446
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: caddy-config
              subPath: Caddyfile
            - mountPath: /data
              name: tmp
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              port: http
              path: /ping
            periodSeconds: 30
          readinessProbe:
            httpGet:
              port: http
              path: /ping
      restartPolicy: Always
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config
        - name: tmp
          emptyDir:
            medium: Memory
