apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: notifiarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`notifiarr.internal`)
      middlewares:
        - name: security-headers
          namespace: kube-system
      services:
        - name: notifiarr
          port: 80
  tls:
    secretName: notifiarr-cert-tls
    domains:
      - main: notifiarr.internal
