apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crosswatch-public-cert
spec:
  secretName: crosswatch-public-cert-tls
  commonName: crosswatch.anshulg.direct
  dnsNames:
    - crosswatch.anshulg.direct
  duration: 2160h0m0s
  renewBefore: 720h0m0s
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  subject:
    organizations:
      - Anshul Gupta
    organizationalUnits:
      - rpi5
    provinces:
      - California
    countries:
      - US
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-public
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`crosswatch.anshulg.direct`)
      middlewares:
        - name: security-headers
          namespace: kube-system
      services:
        - name: crosswatch
          port: 80
  tls:
    secretName: crosswatch-public-cert-tls
    domains:
      - main: crosswatch.anshulg.direct
