apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: crosswatch
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`crosswatch.internal`)
      middlewares:
        - name: security-headers
          namespace: kube-system
      services:
        - name: crosswatch
          port: 80
  tls:
    secretName: crosswatch-cert-tls
    domains:
      - main: crosswatch.internal
