apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../kustomize/base
  - ../../../kustomize/workloads/deployment
  - env.yaml

components:
  - ../../../kustomize/components/security-context

namePrefix: rreading-glasses-
labels:
  - pairs:
      app.kubernetes.io/name: rreading-glasses
    includeSelectors: true

images:
  - name: busybox
    newName: blampe/rreading-glasses
    newTag: hardcover@sha256:91905de54a9da6766d0c28a913b6ab4e26f0ef13e944eb5b514e17affd4732f9

patches:
  - target:
      kind: Deployment
    path: patch-deployment.yaml
  - target:
      kind: Deployment
    path: patch-deployment2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
