apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../kustomize/base
  - ../../../kustomize/workloads/deployment
  - env.yaml

components:
  - ../../../kustomize/components/security-context

namePrefix: rreading-glasses-
labels:
  - pairs:
      app.kubernetes.io/name: rreading-glasses
    includeSelectors: true

images:
  - name: busybox
    newName: blampe/rreading-glasses
    newTag: hardcover@sha256:47c84d4002ecb614bea74a5fba5156a3e249b66c73cc1e8d9dc159315e2bc96e

patches:
  - target:
      kind: Deployment
    path: patch-deployment.yaml
  - target:
      kind: Deployment
    path: patch-deployment2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
