apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/tailscale

namePrefix: prowlarr-
labels:
  - pairs:
      app.kubernetes.io/name: prowlarr
    includeSelectors: true

images:
  - name: busybox
    newName: linuxserver/prowlarr
    newTag: 2.3.2-nightly@sha256:f3b769690a242cfaecf9dde5be25bb96939314463f5ed9f36d845d10efd2e607

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=prowlarr.internal
      - TS_HOST=prowlarr
  - name: env-config
    literals:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
