apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/tailscale

namePrefix: prowlarr-
labels:
  - pairs:
      app.kubernetes.io/name: prowlarr
    includeSelectors: true

images:
  - name: busybox
    newName: linuxserver/prowlarr
    newTag: 2.3.2-nightly@sha256:92fb2bde29cc733ac462df01c1bf78f296a677e4d24a3c6742d58b7cc276ffc1

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=prowlarr.internal
      - TS_HOST=prowlarr
  - name: env-config
    literals:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
